### ISSUE TITLE
add option to try to match specific selector with some unknown args

### ISSUE THREAD

**Issue by wschwab** [botdad/power-clash#1]
Hi! This looks really awesome, I was wondering if I could ask for an additional feature.

Let's say I have a selector I see be used on-chain. I have some ideas what the name is, and I can figure out at least some of the args from the calldata around it. I'd like to be able to suggest a prefix, give the args I do know about, also pass in the selector I'm trying to match against, and try to brute force based on what additional arguments could be in it.

Would it be hard to add something like this? I don't know much Rust, if you know what it would take, maybe I could PR (probably not) or find someone who can.

**Comment by botdad** [comment]
Attempting this is probably better for a tool like `cast` from https://github.com/foundry-rs/foundry

since arguments have a relatively small number of possibilities I'd do it as a shell script like this:

```bash
$ for i in uint256 uint112; do echo $i; cast calldata "functionNameGuess($i)" 1; done
uint256
0xf5d682680000000000000000000000000000000000000000000000000000000000000001
uint112
0x893f260b0000000000000000000000000000000000000000000000000000000000000001
```
